# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FbToken',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='InToken',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='TwToken',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 23, 3, 8, 894378)),
        ),
    ]
