# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_app', '0002_auto_20170902_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 3, 12, 44, 3, 709564)),
        ),
    ]
