# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_app', '0003_auto_20170903_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 3, 16, 48, 28, 411294)),
        ),
    ]
