# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_app', '0004_auto_20170903_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 11, 19, 39, 9, 579453)),
        ),
    ]
