# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_app', '0005_auto_20170911_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='SecTwToken',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='TwToken',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 17, 21, 30, 52, 533541)),
        ),
    ]
