# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_app', '0006_auto_20170917_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 21, 0, 5, 33, 722702)),
        ),
    ]
